name: "terraform-plan-infra-plan"

on:
  push:
    branches:
      - dev

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      GCP_PROJECT: "ianlimle-projects"
      GCP_REGION: "asia-southeast1"
      GCP_ZONE: "asia-southeast1-b"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        id: init
        run: terraform init

      - name: Plan Terraform 
        id: plan
        if: github.event_name == 'push'
        run: terraform plan 

