name: "Terraform-Apply-Infra-Release"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  terraform:
    runs-on: ubuntu-18.04
    env:
      gcp_credentials: ${{ secrets.GCP_CREDENTIALS }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Init Terraform
        id: init
        run: terraform init
      
      - name: Plan Terraform
        id: plan
        if: github.event_name == 'push'
        run: terraform plan -f ./tutorials/main.tf -no-color
        continue-on-error: true
        
      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1
        
      - name: Apply Terraform
        if: github.ref == 'refs/head/main' && github.event_name == 'push'
        run: |
          cd ./tutorials
          terraform apply -auto-approve
